apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: discord-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /webhook/sentry
        pathType: Prefix
        backend:
          service:
            name: discord-service
            port:
              name: fastapi
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: discord-service
            port:
              name: fastapi
      - path: /health/detailed
        pathType: Prefix
        backend:
          service:
            name: discord-service
            port:
              name: fastapi